### ISSUE TITLE
Assertion `qp_init_attr.cap.max_infline_data >= UCT_UD_MIN_INLINE

### ISSUE THREAD

**Issue by mdidomenico4** [openucx/ucx#2592]
I'm trying to run ucx_info -d on my node

when i do i get a bunch of output, but then it ends with

# transport: ud
# device: qib0:1
ud_iface.c:305 Assertion 'qp_init_attr.cap.max_inline_data >= UCT_UD_MIN_INLINE' failed
==== bactrace ====
0 /lib64/libucs.so.0(__ics_abort+0x105] [0x7f7569a62325]
1 /lib64/libuct.so.0(uct_ud_iface_t_init+0x76b) [0x7f756a2b951b]
2 /lib64/libuct.so.0(+0x24d1d)[0x7f756a2bcd1d]
3 /lib64/libuct.so.0(+0x2507a)[0x7f756a2bd07a]
4 ucx_info() [0x402bdc]
5 ucx_info() [0x403856]
6 ucx_info() [0x401b89]
7 /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f7568b73c05]
8 ucx_info() [0x401c41]

this was using version 1.2.2.1.el7 that comes with epel on a redhat 7.5 machine

**Comment by shamisp** [comment]
@yosefe is this the limitation that we have about min inline size ? time to remove it ?

**Comment by yosefe** [comment]
we have it in TODO list: #750

**Comment by miked-mellanox** [comment]
do you use qlogic HCA with ucx?
If so - currently it is unsupported and untested with ucx.

**Comment by miked-mellanox** [comment]
currently not in plans but contributions are welcome!

**Comment by shamisp** [comment]
There is not much difference API wise between OPA / Qlogic. The current
issue is related to the assumption that verbs/ucx developer made about min
inline size in order to avoid bounce buffer allocation. The fix is
relatively simple. Allocate bounce buffer and release it on local
completion. We have never had time to implemented. I would suggest to file
it as bug.

**Comment by yosefe** [comment]
fixed
