### ISSUE TITLE
Graph500 failure when built with clang + OpenMPI + OpenUCX

### ISSUE THREAD

**Issue by nSircombe** [openucx/ucx#2777]
The popular data-intensive HPC benchmark Graph500 generates an apparent memory leak when built with clang, using OpenMPI and OpenUCX built with clang 5.0.2.

First identified with armclang 18.3 on AArch64 running RHEL7. Reproduced with clang 5.0.2 (http://releases.llvm.org/download.html) on x86 running Ubuntu 16.

Benchmark runs to completion and generates multiple warnings of the form...
mpool.c:38   UCX  WARN  object 0x11b3500 was not returned to mpool ucp_requests
...apparently indicative of a memory leak?

### Building OpenUCX as follows:

```
git clone https://github.com/openucx/ucx.git
cd ixc
./autogen.sh
mkdir build
cd build
CXXFLAGS+="-D__STRICT_ANSI__" CC=clang CXX=clang++ ../configure --prefix=<openucx install>
```

### Building OpenMPI v3.1.1 with the following configure line:

```
CXXFLAGS+="-D__STRICT_ANSI__" CC=clang CXX=clang++ ../configure --prefix=<openmpi install> --enable-mpirun-prefix-by-default --enable-mpi-cxx --with-ucx=<openucx install> --disable-f77 --disable-f90 --disable-fc
```

### Building Graph500 with supplied makefile (in `src`, after adding required locations to `PATH`, `CPATH`, `LD_LIBRARY_PATH`, `LIBRARY_PATH`...)

Running Graph500 as follows:

```
mpirun -np 16 ./graph500_reference_bfs 16 16
```

**Comment by shamisp** [comment]
@yosefe can you please take a look

**Comment by shamisp** [comment]
@yosefe were you able to reproduce this ?

**Comment by hoopoepg** [comment]
@shamisp apply this patch to benchmark:
```
diff --git a/aml/aml.c b/aml/aml.c
index 5b70f67..29d4726 100644
--- a/aml/aml.c
+++ b/aml/aml.c
@@ -478,6 +478,10 @@ SOATTR void aml_finalize( void ) {
        for(i=0;i<NRECV_intra;i++)
                MPI_Cancel(rqrecv_intra+i);
 #endif
+    MPI_Status stat_intra[NSEND_intra];
+    MPI_Waitall(NSEND_intra,rqsend_intra,stat_intra);
+    MPI_Status stat[NSEND];
+    MPI_Waitall(NSEND,rqsend,stat);
        MPI_Finalize();
 }
```

**Comment by shamisp** [comment]
@nSircombe can you please check ? Look's like application bug....

**Comment by nSircombe** [comment]
Graph500* works perfectly with AML patched as @hoopoepg suggests.
...I'll raise this with the Graph500 developers.

Thanks for you help!

(* AArch64, Arm HPC Compiler 18.4, OpenMPI 3.1.1 + OpenUCX 1.3)

**Comment by shamisp** [comment]
@hoopoepg thanks for catching this.
@nSircombe probably we can post short FAQ about the issue + patch on UCX Wiki. I'm sure you are not the first one and not the last one. Probably we can open new application section under "Running UCX"

**Comment by yosefe** [comment]
the problem does not seem related to UCX, since according to MPI spec, the application must wait for non-blocking requests to complete. Section "8.7 Startup":

Before an MPI process invokes MPI_FINALIZE, the process must perform all MPI calls
needed to complete its involvement in MPI communications: It must locally complete all
MPI operations that it initiated and must execute matching calls needed to complete MPI
communications initiated by other processes. For example, if the process executed a nonblocking
send, it must eventually call MPI_WAIT, MPI_TEST, MPI_REQUEST_FREE, or
any derived function; if the process is the target of a send, then it must post the matching
receive; if it is part of a group executing a collective operation, then it must have completed
its participation in the operation.
