### ISSUE TITLE
autogen fails on (early?) AS_IF

### ISSUE THREAD

**Issue by alex--m** [openucx/ucx#3540]
Running "autogen.sh" fails with the following error:
```
alex@AlexMN-X1:~/workspace/ucx$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config/m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
autoreconf: running: /usr/bin/autoconf
configure.ac:33: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:34: error: possibly undefined macro: AC_SUBST
configure.ac:137: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:238: error: possibly undefined macro: AC_DEFINE
configure:27019: error: possibly undefined macro: AC_MSG_WARN
autoreconf: /usr/bin/autoconf failed with exit status: 1
alex@AlexMN-X1:~/workspace/ucx$ autoconf --version
autoconf (GNU Autoconf) 2.69
...
```

"git blame" shows this for the relevant lines (around configure.ac:33), so I'm tagging @yosefe and @amaslenn :
```
880306311d (Andrey Maslennikov   2017-07-27 15:28:13 +0300  32) AC_CHECK_PROG(GITBIN,git,yes)
d13ca3fc29 (Yossi Itigin         2019-01-02 20:27:19 +0200  33) AS_IF([test x"${GITBIN}" = x"yes"],
880306311d (Andrey Maslennikov   2017-07-27 15:28:13 +0300  34)       [AC_SUBST(SCM_VERSION, esyscmd([sh -c 'git rev-parse --short=7 HEAD']))],
880306311d (Andrey Maslennikov   2017-07-27 15:28:13 +0300  35)       [AC_SUBST(SCM_VERSION, "0000000")])
880306311d (Andrey Maslennikov   2017-07-27 15:28:13 +0300  36)
```

**Comment by alex--m** [comment]
my bad - misconfiguration of "pkg-config" package... sorry :)

**Comment by hzhou** [comment]
I also hit this error today and scratched my head in frustration for half a day. The error message is rather misleading, so I'll add some notes here to help future encounters.

* `configure.ac:34:` is totally bogus. What happens is `autoconf` find in the output, `configure`, contains unexpanded macro, `AS_IF`. That only means this macro is over-quoted in the source, ie `configure.ac`. In the spirit of being helpful, `autoconf` searches in `configure.ac` for the first occurrence of `AS_IF` and suggesting to the user that that might be the source of corruption -- which is totally not.

* The real occurrence can be traced by comparing `configure` and `configure.ac` and apply manual diligence.  In this case, it points to `src/uct/sm/mm/xpmem/configure.m4`, and it is immediately clear that the culprit is an un-expanded `PKG_CHECK_MODULES` macro. That macro is from  `pkg-config`, therefore, the answer is "missing `pkg-config` package".

**Comment by olejorgenb** [comment]
Thank you @hzhou . I think this is the first post I've found on the problem that actually explains what's going on instead of just suggesting installing something seemingly unrelated (like autoconf-archive or pgk-config)
