### ISSUE TITLE
shm_ib/test_ucp_peer_failure.zcopy fails on boo31

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#3577]
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10164/label=boo31,worker=0/console
```
23:10:46 [ RUN      ] shm_ib/test_ucp_peer_failure.zcopy/3
23:10:50 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/boo31/worker/0/contrib/../test/gtest/common/test.cc:265: Failure
23:10:50 Failed
23:10:50 Got 1 errors during the test
23:10:50 
[  FAILED  ] shm_ib/test_ucp_peer_failure.zcopy/3, where GetParam() = shm,ib (4488 ms)
```

**Comment by dmitrygladkov** [comment]
#3712 fixes the issue
The root cause: UCT/IB/UD EP timeout (3 seconds - set for UCP peer failure test cases) is too small to establsih a connection (wireup) and for data transfer when don't expect errors for IB/UD transport.
Solution: sets UCT/IB/UD EP timeout to 3 seconds after initialization and preparations this timeout is reset to the default value (5 minutes) after peer failure tested.
