### ISSUE TITLE
[Q] Remove SHM_REMAP dependency

### ISSUE THREAD

**Issue by keisukefukuda** [openucx/ucx#3945]
Hi, 
As part of the efforts of porting UCX to MacOS, that @hiroyuki-sato and I are working on, I'd like to remove SHM_REMAP dependency.
I’d like to check if my understanding is correct and I’m on the right track. Any comment or advice is welcome.

macOS does not have SHM_REMAP constant for the SYSV shared memory
(`SHM_REMAP` is actually Linux-specific), and we need to make it optional.

In the `src/` directory,  there are 3 usages of `SHM_REMAP` (and two more usages in the `test/` directory).

(1) src/ucm/mmap/install.c https://github.com/openucx/ucx/blob/master/src/ucm/mmap/install.c#L142
(2) src/ucm/event/event.c  https://github.com/openucx/ucx/blob/master/src/ucm/event/event.c#L282
(3) src/ucs/sys/sys.c  https://github.com/openucx/ucx/blob/master/src/ucs/sys/sys.c#L708

(2) and (3) are basically just a wrapper of the `shm_at()` system call and I think it’s pretty easy to fix. (Just remove the lines on non-SHM_REMAP environments by using `#ifdef HAVE_XXX` macro.

I am not sure about the (1) case.
This is related to UCM event installation. When `ucm_set_event_handler()` is called, the `ucm_fire_mmap_events_internal()` function is (indirectly) called and checks if the event is already watched and determine if it is really needed to install the event.
I’m wondering if we can just remove the SHM_REMAP line on such platforms.

Thanks!
Keisuke

**Comment by hiroyuki-sato** [comment]
Just sharing previous discuss in private mail(@yosefe and @kostikbel).

> (yosefe) Is mmap(MAP_FIXED) supported on Mac OS? We should use it as fallback
> (kostikbel) It should be, MAP_FIXED is very fundamental part of Unix API.  According to the macosx mmap(2) man page, it is.
> (yossi) Good, we already have flows in UCX to try both sysv and mmap methods. Generally speaking, we can disable/bypass sysv.

**Comment by keisukefukuda** [comment]
Thanks Hiroyuki.

So, which is better in this case, to fix each item (such as `SHM_REMAP`) one by one, or totally bypass sysv method? (I don't know mmap method works on MacOS, though).

**Comment by shamisp** [comment]
@yosefe this is all malloc hooks related as far as I can tell. Why would care about this on OSX ?

**Comment by hiroyuki-sato** [comment]
Hello, @yosefe Could you comment about this?

Question is follows.

* Which method(SYSV or mmap) is better on macOS? (macOS doesn't support SHM_REMAP)
* If we choice mmap, is it possible to disable SYSV in the _current_ implementation?
* If that feature not available yet, Could you tell me _how to_ implement it?

Best regards.

**Comment by hoopoepg** [comment]
@yosefe btw it seems bistro mode should be disabled on freebsd & macOS - it is based on direct syscals which may be different on non-linux OSes

**Comment by yosefe** [comment]
adding @kostikbel who is already working on this AFAIK
we have 2 main use-cases of SHM_REMAP in the code:
1. in UCM module (malloc hooks). We can undefine/disable all SHM_REMAP-related flows here: since it doesn't exist, no need to catch it.
2. In UCS module: it's used for allocating shared memory at fixed address. Here' it's not so simple. We should probably return UCS_ERR_INVALID_PARAM if we have non-NULL address for uct_sysv_alloc(), and the callers of that function have to be able to handle that return code and fallback to another allocation method (like in uct_mem_alloc), or expose the fact that fixed allocation is not supported (when used from uct_sysv_alloc), by changing this in case of sysv: https://github.com/openucx/ucx/blob/a8347231a28a50e82845928f4064c0a65cb7b581/src/uct/sm/mm/base/mm_md.c#L136

**Comment by kostikbel** [comment]
> adding @kostikbel who is already working on this AFAIK
I simply implemented SHM_REMAP for FreeBSD, it was the simplest way out.

What you can do if you need SHM_REMAP and accept some not 100% reliable hack is to call munmap(2) before shmat(2).  Fixed-address mappings are somewhat risky anyway, if you do not control the whole address space, and the difference between shmat(SHM_REMAP) vs. munmap/shmat() is that somebody else might mmap into the space between the syscalls.

**Comment by keisukefukuda** [comment]
Thanks for all of your comments and advice.

I think it is acceptable to return `UCS_ERR_INVALID_PARAM` from `ucs_sysv_alloc()` when `SHM_REMAP` is used on MacOS, because it is obvious from the name that the functions is a very thin wrapper of the SYSV system call and thus platform-dependent. 

I will write a patch to do that, as a basis for further discussion.

**Comment by shamisp** [comment]
There are users that care about OpenSHMEM on OSX. 

For symmetric heap OpenSHMEM should use UCX allocator and the base address does *not* have to be the same. 

For static and global variables on OSX we can switch to RMA emulation since we don't really care about performance. This is mostly for people developing on their laptops. It just have to function.

For Freebsd, I guess you do care about performance and it is better to get it resolved. Nevertheless I'm not sure how you going to get performance without something like XPMEM.

**Comment by kostikbel** [comment]
> For Freebsd, I guess you do care about performance and it is better to get it resolved. Nevertheless I'm not sure how you going to get performance without something like XPMEM.

Resolved in which way ?  FreeBSD does have SHM_REMAP, I implemented it, see above.
