### ISSUE TITLE
[Q] How to interpret the put region range? 

### ISSUE THREAD

**Issue by madsbk** [openucx/ucx#4269]
While debugging a problem I noticed that when receiving data to memory address X, I some times encounter put region ranges that that ends at X. I would expect that the put range would go from X to X+nbytes?

Example calling `ucp_tag_recv_nb(..., data=0x7fc115a02000, ...)` could result in:
```
rcache.c:218  UCX  TRACE mlx5_0: put region 0x55b3d45baed0 [0x7fc115a00000..0x7fc115a02000] gt rw ref 2 lkey 0xdd27c rkey 0xdd27c atomic_rkey 0xffffffff
```
Is that expected behavior or am I doing something wrong?

cc @Akshay-Venkatesh, @MattBBaker

**Comment by yosefe** [comment]
@madsbk please attach full trace file

**Comment by madsbk** [comment]
> @madsbk please attach full trace file

Sure, here is the trace: [trace.txt](https://github.com/openucx/ucx/files/3723481/trace.txt)
Notice, the `tag_recv() - data: 0x56161005b240, nbytes: 8` prints are the calls to `ucp_tag_recv_nb`.

**Comment by hoopoepg** [comment]
hi @madsbk 
as I can see from trace:
```
[1571039688.734103] [dgx15:48192:0]         rcache.c:224  UCX  TRACE mlx5_1: put region 0x561610fddc80 [0x7f589da00c00..0x7f589da01000] gt rw ref 2 lkey 0x7ffdb rkey 0x7ffdb atomic_rkey 0xffffffff
tag_recv() - data: 0x7f589da01000, nbytes: 1024
[1571039688.741303] [dgx15:48192:0]          ib_md.c:526  UCX  DEBUG registered memory 0x7f589da01000..0x7f589da01400 on mlx5_1 lkey 0x80ae5 rkey 0x80ae5 access 0x0 flags 0x60
[1571039688.741315] [dgx15:48192:0]         rcache.c:569  UCX  TRACE mlx5_1: created region 0x561610fbbb80 [0x7f589da01000..0x7f589da01400] gt rw ref 2 lkey 0x80ae5 rkey 0x80ae5 atomic_rkey 0xffffffff
[1571039688.741320] [dgx15:48192:0]         ucp_mm.c:124  UCX  TRACE registered address 0x7f589da01000 length 1024 on md[3] memh[0]=0x561610fbbbb0
```

address of buffer at 0x7f589da01000 is displayed as end of buffer of previous operation.
```put region``` trace entry is not data region for RDMA PUT operation, is it debug short meaning that any region of memory is **registered** for HW RDMA PUT operations

**Comment by yosefe** [comment]
@madsbk here it's a coincidence: the region created by previous tag_recv ends at address X, and during the next operation the previous one is completed so its region is unregistered
for example: region `0x561610fbbb80` which ends at `0x7f589da01400` belongs to the first tag_recv
```
tag_recv() - data: 0x7f589da01000, nbytes: 1024
[1571039688.741303] [dgx15:48192:0]          ib_md.c:526  UCX  DEBUG registered memory 0x7f589da01000..0x7f589da01400 on mlx5_1 lkey 0x80ae5 rkey 0x80ae5 access 0x0 flags 0x60
[1571039688.741315] [dgx15:48192:0]         rcache.c:569  UCX  TRACE mlx5_1: created region 0x561610fbbb80 [0x7f589da01000..0x7f589da01400] gt rw ref 2 lkey 0x80ae5 rkey 0x80ae5 atomic_rkey 0xffffffff
[1571039688.741320] [dgx15:48192:0]         ucp_mm.c:124  UCX  TRACE registered address 0x7f589da01000 length 1024 on md[3] memh[0]=0x561610fbbbb0
tag_recv() - data: 0x7f589da01400, nbytes: 1024
[1571039688.741653] [dgx15:48192:0]         ucp_mm.c:71   UCX  TRACE de-registering memh[0]=0x561610fbbbb0 from md[3]
[1571039688.741663] [dgx15:48192:0]         rcache.c:224  UCX  TRACE mlx5_1: put region 0x561610fbbb80 [0x7f589da01000..0x7f589da01400] gt rw ref 2 lkey 0x80ae5 rkey 0x80ae5 atomic_rkey 0xffffffff

```

**Comment by yosefe** [comment]
BTW are you suspecting the local protection error is bug in UCX? does it happen with upstream version?

**Comment by madsbk** [comment]
I see, thanks.
While developing [Python bindings for UCX](https://github.com/rapidsai/ucx-py), we encounter this error. We don't know if it is a problem in the bindings, UCX, or our hardware setup -- it only happens on our DGX machines with InfiniBand.

Is there a way to get UCX to report exactly where the error happens and why?

**Comment by yosefe** [comment]
The problem is the memory key is not valid from HCA perspective. Is this GPU memory? it possible GPU direct drivers are not loaded/enabled/configured properly?
Is it possible to upload a reproducer for this?

**Comment by madsbk** [comment]
Yes, it is GPU memory; running CPU-only works. 
The only way I have been able to reproduce the problem is with [UCX-Py](https://github.com/rapidsai/ucx-py) and only after several GPU messages back and forth. 
If I resets the CUDA context between communication it works, if I don't re-use memory allocations (not calling free) it also works.

**Comment by Akshay-Venkatesh** [comment]
@yosefe @bureddy I've not looked at the problem that madsbk is pointing to in detail but this
> If I resets the CUDA context between communication it works, if I don't re-use memory allocations (not calling free) it also works.

suggests that address recycling is taking place and it's possible that the registration cache that UCX uses may not account for the fact. I could be wrong about this but is it possible that the cache entry is stale because UCX thinks that pointer being viewed and the associated registration entry is valid but in truth the memory backing the pointer (and the virtual address range) has changed and the registration entry is in fact not valid. I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected? 

Previously, this case was explicitly detected in OpenMPI and handled through BUFFER_ID attribute which is unique and isn't recycled. Essentially, BUFFER_ID match was checked to verify if memory registration entry is still valid. Refer https://github.com/open-mpi/ompi/blob/e9e4d2a4bc4ca34d8f426a5f175e3a9eabe50a66/opal/mca/common/cuda/common_cuda.c#L2015 

More details here on buffer:
 
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__UNIFIED.html#group__CUDA__UNIFIED_1g0c28ed0aff848042bc0533110e45820c

CU_POINTER_ATTRIBUTE_BUFFER_ID:

Returns in *data a buffer ID which is guaranteed to be unique within the process. data must point to an unsigned long long.

ptr must be a pointer to memory obtained from a CUDA memory allocation API. Every memory allocation from any of the CUDA memory allocation APIs will have a unique ID over a process lifetime. Subsequent allocations do not reuse IDs from previous freed allocations. IDs are only unique within a single process.

**Comment by madsbk** [comment]
> I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected?

Yes to `UCX_MEMTYPE_CACHE=n`

**Comment by bureddy** [comment]
> > I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected?
> 
> Yes to `UCX_MEMTYPE_CACHE=n`

any reason for not using UCX_MEMTYPE_CACHE=y ?

**Comment by bureddy** [comment]
>  I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected?

@Akshay-Venkatesh  we don't associate cuda mem hooks with MEMTYPE_CACHE on/off.  cuda mem event should be there even when cache is off. we need to understand why cudaFree() not cleared the reg cache entry if that is the case.

**Comment by Akshay-Venkatesh** [comment]
> > > I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected?
> > 
> > 
> > Yes to `UCX_MEMTYPE_CACHE=n`
> 
> any reason for not using UCX_MEMTYPE_CACHE=y ?

Mostly because of these two:
https://github.com/openucx/ucx/issues/4222
https://github.com/openucx/ucx/pull/4261

**Comment by Akshay-Venkatesh** [comment]
> > I'm assuming that `UCX_MEMTYPE_CACHE` has been set to `n` and so the free isn't caught so virtual address recycling may not be detected?
> 
> @Akshay-Venkatesh we don't associate cuda mem hooks with MEMTYPE_CACHE on/off. cuda mem event should be there even when cache is off. we need to understand why cudaFree() not cleared the reg cache entry if that is the case.

@bureddy Do you mean cu*Malloc/cu*Free are intercepted even if they're not cached? If so, then thanks for the clarification and in that case I agree that we need to find why the stale entry isn't removed.
