### ISSUE TITLE
Webex/Remote Viewing of Hackathon

### ISSUE THREAD

**Issue by quasiben** [openucx/ucx#4537]
UCX is organizing an [upcoming hackathon](https://github.com/openucx/ucx/wiki/UCF-Hackathon-2019) next week.  Would it be possible to setup a webex (or equivalent) for others to join in remotely during presentations ?

**Comment by shamisp** [comment]
This is not a bug but a feature request :-) 

Probably we can arrange something. Part of challenge here is that based on the last year meeting experience most of our talks are inteructive board discussions. In this room I don't have digital board :-( Otherwise, I should be able to add Skype call in option to the room.

**Comment by quasiben** [comment]
Hackathon can be remotely viewed with skype: https://meet.lync.com/armh/kelly.lane/BJC7T667

**Comment by jakirkham** [comment]
Thanks all for supporting people viewing remotely. It was greatly appreciated. 😄
