### ISSUE TITLE
UCX fails to compile with clang-9

### ISSUE THREAD

**Issue by spikebike** [openucx/ucx#4549]
### Describe the bug

Compiling with clang-9 fails with:
```
make[3]: Entering directory '/share/apps/src/mpi-2019-10/ucx-1.6.1/src/tools/perf'
  CCLD     ucx_perftest
ld.lld: error: unknown argument '-dynamic-list-data'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to Reproduce
```
./configure --prefix=/share/apps/ucx-1.6.1/aocc2 --enable-mt --with-avx --with-verbs
make
```

### Setup and versions

I'm using Ubuntu 18.04 and clang version 9 (as packaged from AMD with AOCC-2.1)

I manually removed "-Wl,-dynamic-list-data" from various make related files and it seems to compile fine.

**Comment by spikebike** [comment]
This happens in the 1.7.0 RC as well.

**Comment by yosefe** [comment]
`-Wl,-dynamic-list-data` was needed for memtype support in ucx_perftest, because the global array of memory type handlers should be visible from loaded modules

**Comment by hoopoepg** [comment]
hi @spikebike 
could you run your version of compiler with parameter ```--version``` & provide output here?

thank you

**Comment by lyu** [comment]
Please allow me to chime in since I have encountered this exact problem before.

This probably has nothing to do with the version of clang since it's the LLVM's LLD used during linking that doesn't support `-dynamic-list-data`, even for the latest 9.0.0 version.

I had to work around this by specifying `-fuse-ld=bfd` or `-fuse-ld=gold` in `LDFLAGS` to force the use of the GNU linkers.

However, `configure` doesn't detect the linker used by the current compiler correctly, it always shows `$PATH/ld` no matter what linker is actually used, like:

```
checking for ld used by clang++... /gpfs/home/USER/.local/bin/ld -m elf_x86_64
checking if the linker (/gpfs/home/USER/.local/bin/ld -m elf_x86_64) is GNU ld... yes
```

**Comment by MaskRay** [comment]
`--dynamic-list-data` is not useful. If the intention is to make variable interposable in the presence of `-Bsymbolic`, just use `-Bsymbolic-functions` instead. I don't think ld.lld should add this option.

**Comment by EladgNext** [comment]
note that [PR-7778](https://github.com/openucx/ucx/pull/7778) replaces  `--dynamic-list-data` with `--export-dynamic`, and thus solves this issue (or at least should) 
 :)
