### ISSUE TITLE
How does UCX choose the correct transport at runtime? [Question]

### ISSUE THREAD

**Issue by Yiltan** [openucx/ucx#5800]
I'm currently working with OMPI + UCX and to run my applications I have been using the following command:
```
mpirun -np 2 --mca pml ucx -x UCX_TLS=rc,sm,cuda_copy,gdr_copy,cuda_ipc ./application
```

From my understanding the environment variable `UCX_TLS` tells UCX which transports are available for it to use. The code I have read using the tag send/recv API, they have just passed a device or host pointer into the function and it is handled automatically.

**Question:** How does UCX determine if the send/recv is sending from device to host or device to device and thus which transport to use?

**Comment by dmitrygx** [comment]
UCX has an abstraction for transport called UCT (T stands for transport). During establishing UCP (P stands for protocol, the UCP API is used by OMPI) connection to a peer, UCP queries all available devices and its characteristics from all available UCTs (e.g. CUDA TLs couldn't exist, since UCX was built w/o CUDA support).
After all TL:device pairs are selected, UCP go through all requested features (TAG, RMA, Atomics (AMO) and etc) and decides which transport better fits criteria (i.e. has better performance for some feature). Also, UCP could select multiple TL:device pairs for doing RMA or TAG/AM RNDV to achieve better bandwidth. In addition, UCP select CUDA/RoCM TLs (e.g. `cuda_copy`, `gdr_copy`, `rocm_copy`, `rcom_gdr`) for copying data from host buffer to GPU buffer and vice versa, when host buffers are used as staging buffers when GPU Direct is not supported by the IB transport.
Regarding `UCX_TLS`, you're absolutely right. `UCX_TLS` gives a hint to the UCP which transport it could use during selection logic.

**Comment by shamisp** [comment]
@dmitrygx We should actually move this to FAQ on read-the-docs

**Comment by yosefe** [comment]
> @dmitrygx We should actually move this to FAQ on read-the-docs

https://openucx.readthedocs.io/en/master/faq.html#selecting-networks-and-transports

**Comment by Yiltan** [comment]
Thank you for the help, this is useful and puts me on the right track

**Comment by shamisp** [comment]
@yosefe this answers much more descriptive. I can move it to FAQ.

**Comment by UESlubei** [comment]
@dmitrygx , hello, I am currently studying UCX communication , I want to know the meaning of "transport selection ". Dose it refer to the choice of the transport layer(such as tcp or rc etc ) or the choice of the protocol (eager,rndv ). If it is the choice of the transport layer, what is the logic of this choice? Can I get it in the part of the source code?
