### ISSUE TITLE
Some questions about ucx for a new beginner

### ISSUE THREAD

**Issue by zhangwp** [openucx/ucx#5927]
Now，we have a SDS solution. SDS solution have several nodes in cluster, each node run many apps. Apps will communicate with each other intra-node and other nodes' apps inter-node. 
We plan to use ucx shared memeory for apps communication in node, and use rdma(rc) for apps communication between nodes.

**So, I has some questions about this design:**
1. This design is suitable or has technical risk?
2. How to deploy client side and server side？Each app must have client and server？
3. The communication packages is keeped order by ucx default？
4. Can ucx run in spdk context（for example, spdk thread, spdk poll context）
5. What is the relationship between Ucx and libFabric. LibFabric is equal to uct part.
6. How to get started with the ucx which is difficult for a new beginner. ucx has no demos to study.

Thanks！！！

**Comment by shamisp** [comment]
1. In order to discuss technical risks we need to understand the use-case. I don't think the issue has enough background to make the assessment. In terms of OpenUCX code quality - it is production project that is commercialized by vendors.
2. This also answers (6). Our example directory has few easy to basic "hello world" examples, including server/client : https://github.com/openucx/ucx/tree/master/examples
3. Depends on what API is used. Sends/receive and stream communication is ordered. Put/Gets not orders unless you explicitly use fence directive.
4. I'm not familiar with the technical details of SPDK but I don't see why it cannot be used in conjunction with other libraries.
5. There is no relation between the two project. UCX community works in close collaboration with rdma-core community and we are complementary API to the low-level Verbs API developed by rdma core.
6. Since you are asking questions related to I/O I think this example app can be relevant for your use-case https://github.com/openucx/ucx/tree/master/test/apps/iodemo

**Comment by zhangwp** [comment]
> 2. This also answers (6). Our example directory has few simple "hello world" examples, including server/client : https://github.com/openucx/ucx/tree/master/examples
--> Reply: These demos appear a peer to peer program model. Server is not central. So every app using ucx must have both client and server side. If we have many apps that commute with each other, that results in sessions between apps will be more complex.
**Is my understanding correct?**

> 6. Since you are asking questions related to I/O I think this example app can be relevant for your use-case https://github.com/openucx/ucx/tree/master/test/apps/iodemo
--> Reply: Thanks, this demo is useful for me.

**Comment by zhangwp** [comment]
> 2. This also answers (6). Our example directory has few simple "hello world" examples, including server/client : https://github.com/openucx/ucx/tree/master/examples
**--> Reply:** These demos show a peer to peer program model, server is not central. That means app using uxc must has client side and server side, for it can not communicate with other apps using ucx. If we have many apps using ucx, sessions between apps will very complex.
**Is my understanding correct?**

> 3. Depends on what API is used. Sends/receive and stream communication is ordered. Put/Gets are not ordered unless you explicitly use fence directive.
**--> Reply:** RDMA uses Put/Get operation，can not use Sends/receive operation. That means RDMA(RC) is not ordered. Is it right?

> 4. I'm not familiar with the technical details of SPDK but I don't see why it cannot be used in conjunction with other libraries.
**--> Reply:** SPDK use poller mechanism, avoiding context switch that costs performance. Ucx use progress mechanism. I see progress is a kind of poll ?

> 6. Since you are asking questions related to I/O I think this example app can be relevant for your use-case https://github.com/openucx/ucx/tree/master/test/apps/iodemo
**--> Reply:** Thanks, this demo is useful for me.

**Comment by yosefe** [comment]
> **--> Reply:** These demos show a peer to peer program model, server is not central. That means app using uxc must has client side and server side, for it can not communicate with other apps using ucx. If we have many apps using ucx, sessions between apps will very complex.

io_demo example shows multi-server/multi-client scenario

>  **Reply:** RDMA uses Put/Get operation，can not use Sends/receive operation. That means RDMA(RC) is not ordered. Is it right?

Put/Get API are not ordered, but Active Messages an Tag API are ordered

> **--> Reply:** SPDK uses poll mechanism, not event mechanism. It can avoid context switch that costs performance. Ucx use progress mechanism. In my opinion, progress is a kind of poll?

Yes, progress is polling.

**Comment by zhangwp** [comment]
> 
> io_demo example shows multi-server/multi-client scenario
> 
**Reply:** UCX can used in distributed storage scenario, not only in MPI/HPC scenario. Is it right?
> 
> Put/Get API are not ordered, but Active Messages an Tag API are ordered
> 
**Reply:** RDMA(RC) and tcp transport level can use am and tag api, right?

Thanks for your reply!

**Comment by yosefe** [comment]
> **Reply:** UCX can used in distributed storage scenario, not only in MPI/HPC scenario. Is it right?

Yes, that is right

> Reply: RDMA(RC) and tcp transport level can use am and tag api, right?

Yes, every kind of transport can be used with any API

**Comment by shamisp** [comment]
@zhangwp You confuse between API semantic and IBTA RDMA RC semantic. These two are not the same. UCX defines own communication semantics (as defined in API description), which is implemented on variety interconnect technologies including IBTA RDMA RC. IBTA RC provides ordering guarantees for RC QP. Nevertheless, UCX implement multiple communication protocols on top of RC (multi-rail, etc) which implement own semantics that is portable across variety of interconnects (TCP, shared memory ,etc.) The UCP API and communication semantics is the same across difference interconnects.

**Comment by zhangwp** [comment]
> @zhangwp You confuse between API semantic and IBTA RDMA RC semantic. These two are not the same. UCX defines own communication semantics (as defined in API description), which is implemented on variety interconnect technologies including IBTA RDMA RC. IBTA RC provides ordering guarantees for RC QP. Nevertheless, UCX implement multiple communication protocols on top of RC (multi-rail, etc) which implement own semantics that is portable across variety of interconnects (TCP, shared memory ,etc.) The UCP API and communication semantics is the same across difference interconnects.

Thanks, i got it a lot from your reply. 
I have another question. Shared memeory transport does not have ordering guarantee. Who will(should) guarantee the ording? UCX or my application?

**Comment by yosefe** [comment]
> * Shared memeory transport does not have ordering guarantee. Who will(should) guarantee the ording? UCX or my application?

Need to use UCP fence and flush APIs to force strict ordering when needed

> * If UXC use multi-threads mode, it supports lock-free and guarantee the safty of resources?

Thread safe mode guarantees safety with multiple threads, but it is not lock free. In order to get good multi-thread scalability it's recommended to create multiple worker objects. ucx_perftest benchmark demonstrates on option to do this - worker per thread.

**Comment by shamisp** [comment]
I will just add that on hardware that grantees ordering (like shared memory on x86) the UCP fence is effectively translated to `no-op` so the overhead of the API call on ordered interconnects is minimal. Flush can provide ordering grantees but it is somewhat overkill since it also enforces completion semantics - a.k.a messages not just ordered but also completed.

**Comment by zhangwp** [comment]
Thank you very much!!!
