### ISSUE TITLE
Segfault when using AM with alltallv algorithm

### ISSUE THREAD

**Issue by rlgraham32** [openucx/ucx#6328]
When running the test code enclosed I get the following segfault:

Caught signal 11 (Segmentation fault: address not mapped to object at address 0x14a300000000)
This occurs within the ucx worker progress, and specifically in the AM code path.  I am not able to get traceback, so do not have on to provide.

### Steps to `Reproduce`
Test `code:
[a2av.txt](https://github.com/openucx/ucx/files/5971747/a2av.txt)

command line:
mpirun -np 4 -x UCX_HANDLE_ERRORS=bt -x UCX_LOG_LEVEL=data --mca opal_common_ucx_opal_mem_hooks 1 -x HCOLL_BCOL_HYBRID_ALLTOALLV_SEND_LIMIT=0 -x UCX_RNDV_THRESH=4 -x HCOLL_BCOL_HYBRID_ALLTOALLV_AGGREGATE=0 --tag-output -x HCOLL_BCOL_ALLTOALLV_EXCHANGE_ALG=2 -x HCOLL_BCOL_BASE_VERBOSE=100 -x HCOLL_BCOL_ALLTOALLV_MAX_AGG_BUFF_SIZE=64 ./a2av 4 1 0

complile line:  mpicc a2av.c -o a2av

Using tar ball of Open MPI version 4.0.1 (do not think that is relevant)
Using UCX trunk
HCOLL version; repo is  rlgraham32/hcoll and the branch is a2av_timer

**Comment by rlgraham32** [comment]
Addubg config lines:

UCX: 
 ./configure --prefix=/global/home/users/richardg/projects/palltoallv/ucx --with-knem --without-java --enable-devel-headers --without-cuda --without-gdrcopy --enable-debug

HCOLL:

  $ ./configure --prefix=/global/home/users/richardg/projects/palltoallv/hcoll_rich/hcoll --with-ucx=/global/home/users/richardg/projects/palltoallv/ucx --without-sharp --enable-debug

Open MPI:
 ./configure --prefix=/global/home/users/richardg/projects/palltoallv/ompi_hcoll_rich/openmpi-4.0.1 --disable-oshmem --enable-mpi1-compatibility --with-slurm --with-hcoll=/global/home/users/richardg/projects/palltoallv/hcoll_rich/hcoll --with-ucx=/global/home/users/richardg/projects/palltoallv/ucx --with-platform=contrib/platform/mellanox/optimized --enable-debug

**Comment by brminich** [comment]
There are a couple of errors in AM API usage in hcoll code:
1. There is no need to call `ucp_am_data_release()` inside the AM data callback. The rule is the following:
   - If you do not need to access this data outside the AM data callback, just return UCS_OK, no need to invoke `ucp_am_data_release()`
   - If you want to keep using arrived data outside AM data callback need to return UCS_INPROGRESS from this callback. Then when data is no longer needed, it should be freed by ucp_am_data_release()

2. If RNDV request arrived in the data callback and you want to invoke ucp_am_recv_data_nbx() later (outside of data callback), **UCS_INPROGRESS** must be returned.  Otherwise, if UCS_OK is returned, UCP will just free the incoming RTS and will send ACK to the sender to complete its request.

**Comment by brminich** [comment]
@rlgraham32, can we close it?

**Comment by rlgraham32** [comment]
yes

**Comment by brminich** [comment]
added check for such faulty scenario in #6724
