### ISSUE TITLE
use more efficient hash table to manage endpoints

### ISSUE THREAD

**Issue by yosefe** [openucx/ucx#634]
we need a hash table which grows automatically with scale so lookup time would remain nearly constant.
[uthash](https://troydhanson.github.io/uthash) may be a good fit.

**Comment by shssf** [comment]
@yosefe , @brminich 
I implemented a performance test in gtest (test_datatype.queue_perf_hash) with performance comparison for **sglib**, **uthash** and std::map (the last one is useless but interesting).
I used data structure is the same as ucp_ep_t (at least in case of size).

I found **sglib has the best lookup performance** (if number of elements in hash less than predefined) but has some performance issue in initialization and clean-up stages.

This picture shows initialization stage (sglib data for several small numbers of elements erased to make the picture readable):
![image](https://cloud.githubusercontent.com/assets/19515906/16171775/e2fa4404-3580-11e6-9260-9ab1b5a50839.png)

This picture shows look-up stage (sglib data for several large numbers of elements erased to make the picture readable):
![image](https://cloud.githubusercontent.com/assets/19515906/16171777/f543baaa-3580-11e6-9645-bdc30e011c84.png)

Clean-up stage:
![image](https://cloud.githubusercontent.com/assets/19515906/16171781/04d65766-3581-11e6-9c5d-c26b479863ea.png)

System memory consumption (RSS):
![image](https://cloud.githubusercontent.com/assets/19515906/16171783/1155b806-3581-11e6-8ecc-88ea68788aab.png)

I tried to optimize uthash performance but has no luck in this.
The test source is attached.

[test_datatype.txt](https://github.com/openucx/ucx/files/321802/test_datatype.txt)


All numbers and pictures are in attached spreadsheet.
[issue_634.xlsx](https://github.com/openucx/ucx/files/321801/issue_634.xlsx)

Thank you
Sergey

**Comment by yosefe** [comment]
We should stick with sglib then. Let's talk about it on the conf call, for now no point to integrate uthash - since it is both slower and consumes more memory.

**Comment by shssf** [comment]
@yosefe 
May be we can look on this from another perspective. Strictly speaking, we don't need the "world fastest hash" but we need O(1) lookup for UCX internal structures.
Could we add virtual address of the object into the key (or some auxiliary information to speedup look-up procedure)?
ok, let's talk about it on conf call.

**Comment by yosefe** [comment]
putting this on hold, until we find a better hash implementation.
for now - let's add the size if UCP hash to ./configure parameters

**Comment by yosefe** [comment]
@shssf pls provide results when key is a random number

**Comment by shssf** [comment]
**Highlights**

1) Added two more hashes:

- std::unordered_map (as same hash as requested SGI STL hash_map. Mixing std and sgi STL became difficult in same gtest environment)
- khash from Klib tool set http://attractivechaos.github.io/klib/ (under MIT/X11 license)

2) **khash looks good** candidate for sglib replacement:

- low memory consumption
- approximately same or better performance than sglib
- doesn’t require pre-allocated memory (much better initialization and clean-up performance)

3) The keys in the test changed to random
4) Used ucs_generate_uuid from UCS
5) Shuffled the sequence by std::random_shuffle() after key array generation (not necessary since ucs_generate_uuid() provides random keys but used)
6) Small bug in uthash usage fixed – it uses 32 bit keys by default. Changed to 64 bit keys with the same uthash interface functions

**Lowlights**
Previous results were obtained with **“develop” mode UCX**. further performance comparison will be provided with **“release” UCX configuration**. The performance results with “develop” configuration and new hashes (including all additions described above) are provided in attached spreadsheet.

**Details**
Source of the test is here https://github.com/shssf/ucx/blob/active_message_2/test/gtest/ucs/test_datatype.cc#L533

The most interesting is the performance of the look-up for different hashes. Since some measurements make the graph difficult to read, I added the table with performance scores.
![image](https://cloud.githubusercontent.com/assets/19515906/16355651/105fbd30-3ac6-11e6-85f3-ada7f954e3ad.png)
![image](https://cloud.githubusercontent.com/assets/19515906/16355652/1a2e62ee-3ac6-11e6-8962-3e8f245ab87c.png)

Initialize time (the graph starts from 256 number of structures)
![image](https://cloud.githubusercontent.com/assets/19515906/16355660/5a12a406-3ac6-11e6-8796-7bf3d82cf754.png)

The numeric performance scores of initialize time for small number of structures in the hash
![image](https://cloud.githubusercontent.com/assets/19515906/16355663/7b144bf0-3ac6-11e6-8f9d-4287f67ed898.png)

System memory consumption
![image](https://cloud.githubusercontent.com/assets/19515906/16355672/b62533bc-3ac6-11e6-8610-328b9961d5bc.png)

All other performance scores are in attached spreadsheet
[issue_634.xlsx](https://github.com/openucx/ucx/files/332986/issue_634.xlsx)

Thank you
Sergey

**Comment by yosefe** [comment]
@shssf looks like khash is same or better than sglib in all aspects, including memory consumption and lookup performance at scale. So let's replace ucp ep hash with khash:
- add khash.h file to UCX (as is).
- add the performance test (w/o uthash - only sglib,map,unordered_map,khash).
  - make it fail if performance is unreasonable
- replace sglib in ucp by khash, remove ucp_ep_t::next
