### ISSUE TITLE
What is the differences between "tag", "am" and "stream" ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6848]
Hello,

When I use ucx_perftest to do some tests，I see there are some options after -t, such as  "tag", "am" and "stream".
What is the differences between "tag", "am" and stream ? Is there any documentation explains this ?
![image](https://user-images.githubusercontent.com/58133919/119494135-8ab6a580-bd93-11eb-9454-f638bcd7a803.png)

Any reply will be appreciated.

**Comment by yosefe** [comment]
@h2cw2l please see https://openucx.github.io/ucx/api/v1.10/html/md__hpc_mtr_scrap_users_yosefe_ucx_docs_doxygen_design.html

**Comment by h2cw2l** [comment]
> @h2cw2l please see https://openucx.github.io/ucx/api/v1.10/html/md__hpc_mtr_scrap_users_yosefe_ucx_docs_doxygen_design.html

Thanks for reply.

But I want to know their features and applicable scenarios separately.
By reading the doc, I still can't understand it clearly.
Could tell me there feature and  applicable scenarios ?

Stream is reliable ? Others are not reliable ?
The size of a single send through Stream is not fixed ? Others need to be fixed ?

Thank you.

**Comment by yosefe** [comment]
Sure,

1. All UCP APIs are reliable and support any size
2. Tag and Active Message are message-oriented: the receive will be called once per sent message, and receive buffer must be >= send buffer size. Stream API, on other hand, is like TCP: multiple sends could be extracted by a single receive, and vice-versa.
3. Tag is intended mostly for MPI libraries since it has the same semantics as MPI. It's also used as a point-to-point backend for collective libraries.
4. Stream is intended to be an easy replacement for applications/layers using TCP in streaming mode
5. Active message is more generic, it can be used by many types of applications including RPC, IO, Spark shuffle, parameter servers, and more.

**Comment by shamisp** [comment]
@yosefe probably this shell go to FAQ
