### ISSUE TITLE
I want to use gdb to debug example ucp_hello_world, but there are no symbols，what I need to do to use gdb ?

### ISSUE THREAD

**Issue by h2cw2l** [openucx/ucx#6886]
![image](https://user-images.githubusercontent.com/58133919/120465255-59ac2580-c3d0-11eb-9a5a-66ad1369bd67.png)

**Comment by shamisp** [comment]
The file that you use in your example is not a binary but libtool generated script, since you are running from build tree. GDB actually complained that the file is not an executable. This is useful educational link about debug: https://stackoverflow.com/questions/12148668/how-to-debug-a-program-wrapped-in-a-libtool-script

**Comment by h2cw2l** [comment]
> 
> 
> The file that you use in your example is not a binary but libtool generated script, since you are running from build tree. GDB actually complained that the file is not an executable. This is useful educational link about debug: https://stackoverflow.com/questions/12148668/how-to-debug-a-program-wrapped-in-a-libtool-script

Thanks.
