### ISSUE TITLE
Question: one server connects with multiple clients in parallel

### ISSUE THREAD

**Issue by jli111** [openucx/ucx#7726]
### Describe the bug
I am building a client-server system with UCX apis in my project, and encountering some questions and confusions. I have spent some time on this but still cannot solve my problem, would like to seek for kind advice and help.

Following the client-server example code, I notice that there is one server context, one listener worker and one  data worker to handle communications between server and client. I launch one client on a different host, the connection is established as expected. But if I launch multiple clients with mpirun, only one client can be detected and connected. I can see that the server is set to accept only one connection and reject others, however, my first question is:

- Even though the server can only accept one connection request, it's supposed to see other requests and decide to reject them, while why does the server can not detect other connection requests before decide to accept or reject them?

<img width="641" alt="image" src="https://user-images.githubusercontent.com/29782239/143911814-31b692d7-9d0d-484c-8fc1-6fa10dfc5344.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/29782239/143911843-169fa277-02aa-45b6-a929-33189fe5a647.png">

In order to connect with multiple clients in parallel, I did some attempts. 
In my understanding, one connection context can only be associated with one server endpoint and one data worker for one clients. When initialize the server context, I created an array of ucx_conn_request_h, array of data worker, and server endpoints (still only one listening worker).

<img width="676" alt="image" src="https://user-images.githubusercontent.com/29782239/143913801-a020aba7-5f10-4f02-a6fd-56aa4a35ef52.png">

When a connection request is coming, in the connection callback, the incoming connection context will be stored and assigned to different workers and endpoints.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/29782239/143928293-c7d00f06-7b0e-4fdd-b15b-82c0d3c28f0f.png">
<img width="749" alt="image" src="https://user-images.githubusercontent.com/29782239/143928418-9017fa7f-1a7e-4545-a2d3-68ffe1e0cb88.png">

However, this method doesn't work out, the server still can only see and accept one connection request, even with 'worker_params.thread_mode = UCS_THREAD_MODE_MULTI;' when initializing workers. This leads to my second question:

- What is the proper way to accept multiple clients in parallel? Could you please point me to any examples or application codes? 

Appreciate for any reply and advice!

### Setup and versions
$ ucx_info -v
UCT version=1.12.0 revision 75e01e5
configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/root/ucx/fast/install

**Comment by evgeny-leksikov** [comment]
Hi @jli111, according to code from the description I think server gets 2 connection requests and stores them to the same memory `context->conn_request[context->num_conn]`, so it creates endpoint only for the last one but others are lost
can you try to change related code like this: 
`context->conn_request[context->num_conn++] = conn_request;`
and then need to progress incoming connection requests in the loop.

Also, using of array looks not scalable to me, though if server knows number of clients then it's OK I would suggest to use other type of data structure like queue or linked list for this. You can find another example here https://github.com/openucx/ucx/tree/master/test/apps/iodemo
we handle incoming connection here https://github.com/openucx/ucx/blob/6ee161f0e720551f9affafc9b05acddb9cd55355/test/apps/iodemo/ucx_wrapper.cc#L288
and progress them here https://github.com/openucx/ucx/blob/6ee161f0e720551f9affafc9b05acddb9cd55355/test/apps/iodemo/ucx_wrapper.cc#L415

**Comment by evgeny-leksikov** [comment]
Forgot to mention that [ucp_client_server.c ](https://github.com/openucx/ucx/blob/master/examples/ucp_client_server.c) example does not support concurrent connection establishment from multiple clients on server side to keep it simpler:
https://github.com/openucx/ucx/blob/6ee161f0e720551f9affafc9b05acddb9cd55355/examples/ucp_client_server.c#L827

**Comment by chenyidu** [comment]
In ucp_client_server.c, only one thread is performing the following operations
1. Receive a conn_request.
2. Create a ucp ep based on the conn_request,
3. Execute the receiving/sending task.

Currently, UCX doesn't seem to support REUSE_PORT, so you can only get an fd for the listening address, and you can only execute op 1 in one thread. If I understand your needs correctly, all you need is to queue the conn_request in the listener thread and create other threads to execute op 2 and op 3 in parallel. 

Because there is only one ucp_data_worker, you need to specify `--enable-mt` when configuring. Otherwise, `worker_params.thread_mode = UCS_THREAD_MODE_MULTI` does not take effect.

**Comment by evgeny-leksikov** [comment]
it's unrelated to REUSE_PORT since every endpoint created on server side gets its own port.
you can use any number of threads and/or workers but container where connection requests are stored should be thread safe or separated.
In initial issue all connections requests are stored at the same pointer, there is a race.

**Comment by chenyidu** [comment]
> it's unrelated to REUSE_PORT since every endpoint created on server side gets its own port. you can use any number of threads and/or workers but container where connection requests are stored should be thread safe or separated. In initial issue all connections requests are stored at the same pointer, there is a race.

I agree with you that conn_request must be queued, not stored in one place. I mention REUSE_PORT to show that it is not possible to receive conn_requests in parallel because there is only one listener. Actually, you can only run op 2 and op 3 in parallel using multiple ucp worker (because of the ucp worker lock, multiple ucp workers are needed).

**Comment by evgeny-leksikov** [comment]
@chenyidu thanks for clarification! Now I see your point, you are right.
In addition to above - if `ucp_ep_create` was called on different workers which are progressed from different threads, then connection establishment will be performed in parallel, the only serialized place is connection request queue on server.

**Comment by jli111** [comment]
Wonderful! Many thanks to @chenyidu and evgeny-leksikov for answering my question and the demo code!
All questions are clear now, closing the issue.
