### ISSUE TITLE
best practise for handle multiple connections?

### ISSUE THREAD

**Issue by wu-hanqing** [openucx/ucx#8975]
Our distributed storage system uses the UCX library to accelerate the network using RDMA, and the storage server uses the Raft algorithm to replicate user data to ensure high availability and consistency.

In practice, each storage server both establishes links to and accepts links from other nodes.

Each server uses only one ucp_worker (using poll mode), which serially handles establishing links, accepting links from other nodes, sending and receiving data, etc.

During some tests, we found that a single ucp_worker_progress call sometimes consumes a few seconds, basically on ucs_callbackq_slow_proxy (mostly also on link creation/destruction), and this problem causes a timeout on new links from other nodes (this timeout is defined by us). After the timeout, the link is closed, and after waiting for a while, a new link is reattempted. Eventually, none of the nodes can complete the link creation between them. (It is possible that this problem is because we are creating/closing too many links, but we have not identified the exact problem point yet).

I would like to get your answers to the following questions
1. Is there any interface to get the status of ucp links so that we can detect the status of ucp links when reaching timeout, and if it is in progress, then we can wait for a while.
2. Is it safe to call ucp_ep_create and ucp_worker_progress concurrently on the same ucp_worker?
3. other suggestions for this scenario?

**Comment by evgeny-leksikov** [comment]
Hi @wu-hanqing , thank you for reporting!

> Is there any interface to get the status of ucp links so that we can detect the status of ucp links when reaching timeout, and if it is in progress, then we can wait for a while.

Maybe `ucp_ep_query` could help for debugging

> Is it safe to call ucp_ep_create and ucp_worker_progress concurrently on the same ucp_worker?

it's safe if UCX is built and initialized in multithreading mode, but i don't think it can help significantly since these functions have common lock in MT-mode. You can try to create EPs from connect request callback on server side.

Basically, few seconds looks too long for single `ucp_worker_progress` call. Which transports do you use and how many concurrent connections are establishing?
Can you check process state during this? D-state could mean that there are some IO operations like QP create/destroy
How long EP is living? Maybe use pool of connections (EPs) and reuse them?

**Comment by wu-hanqing** [comment]
Apologies for the delayed response. We discovered some bugs in our code that were causing a delay in processing client-side connection requests. We have resolved the issue and everything works fine now.
